Repository hwakabh/clockio, pull requests merged in 2024-06, with the labels that each got.

#5 feat: repository initializations
  .github/config/release-please-config.json
  .github/workflows/release-please.yml
  .gitignore
  .release-please-manifest.json
  label-defaults.json
Labels: ci, features, chore

#11 chore: updated renovate config.
  renovate.json
Labels: deps, renovate, chore

#7 Introduced START_OFFSET_MIN configurable as environment variable
  README.md
  kot_selenium.py
Labels: features

#16 docs: renamed repo and fixed png links
  README.md
  img/google_calendar.png
Labels: docs, chore

#18 docs: fixed minor stdout changes.
  README.md
Labels: docs, chore
